### ISSUE TITLE
SmartThings Installation Error

### ISSUE THREAD

**Issue by ala7470** [KristopherKubicki/device-yamaha-rx#1]
I try to import the app but I am getting this error. 

No signature of method: script1445224053739259461958.metadata() is applicable for argument types: (script1445224053739259461958$_run_closure2) values: [script1445224053739259461958$_run_closure2@1d3787b0] Possible solutions: getMetadata(), getState(), setState(java.lang.Object), metaClass(groovy.lang.Closure)

**Comment by petrusluyt** [comment]
me too

**Comment by KristopherKubicki** [comment]
Hey guys - try installing it as a new Device Type, not as a SmartApp.  That should do it for you!
