### ISSUE TITLE
install

### ISSUE THREAD

**Issue by rb1980** [KristopherKubicki/device-yamaha-rx#2]
Hi, i'm brand-spankin new to smartthings and am scratching my head trying to figure out how to implement your device code. Could you add some basic installation/setup instructions? thanks

**Comment by KristopherKubicki** [comment]
Hey @rb1980 -- Just copy and paste the device code into "New Device Type" under the SmartThings IDE.  Then, go to the tab that says "My Devices" and create a new device.  You then select the Yamaha device from the Device Type drop down (should be the last one).  Then you're set!
